### ISSUE TITLE
doesn't build on OpenBSD due to neoid deps

### ISSUE THREAD

**Issue by ITwrx** [theAkito/nim-quickcrypt#1]
#### Required Information
Project version
quickcrypt@0.1.4
Distro version
OpenBSD 6.8
Kernel version
OpenBSD host.my.domain 6.8 GENERIC.MP#5 amd64

#### Steps to reproduce
nimble install quickcrypt

#### Expected behaviour
installs quickcrypt successfully
#### Actual behaviour
nimble fails to install quickcrypt. it looks like to me that neoid tries to install winim as a incorrectly assessed dependency. winim understandably fails to install, as the platform is not actually windows.

#### Extra details
```
nimble install quickcrypt
Downloading https://github.com/theAkito/nim-quickcrypt using git
  Verifying dependencies for quickcrypt@0.1.4
 Installing nimAES@>= 0.1.2
Downloading https://github.com/jangko/nimAES using git
  Verifying dependencies for nimAES@0.1.2
 Installing nimAES@0.1.2
   Success: nimAES installed successfully.
 Installing neoid@>= 0.3.0
Downloading https://github.com/theAkito/nim-neoid using git
  Verifying dependencies for neoid@0.3.1
 Installing random@>= 0.5.7
Downloading https://github.com/oprypin/nim-random using git
  Verifying dependencies for random@0.5.7
 Installing random@0.5.7
   Success: random installed successfully.
 Installing winim@>= 3.4.0
Downloading https://github.com/khchen/winim using git
  Verifying dependencies for winim@3.6.0
 Installing winim@3.6.0
   Building winim/winim/winimx using c backend
ld: error: /tmp/nimble_26954/githubcom_khchenwinim_3.4.0/winim/lib/winim64.res: unknown file type
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang   -o /tmp/nimble_26954/githubcom_khchenwinim_3.4.0/winim/winimx  /tmp/nimble_26954/githubcom_khchenwinim_3.4.0/winim/lib/winim64.res /home/itwrx/.cache/nim/winimx_r/miniz.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_assertions.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_io.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_system.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_hashes.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_math.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_tables.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_parseutils.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_unicode.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_strutils.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_streams.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_lexbase.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_parsejson.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_json.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_sets.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_sequtils.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_pathnorm.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_posix.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_times.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_os.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_parseopt.nim.c.o /home/itwrx/.cache/nim/winimx_r/@mwinstr.nim.c.o /home/itwrx/.cache/nim/winimx_r/@mlib@sminiz.nim.c.o /home/itwrx/.cache/nim/winimx_r/stdlib_strformat.nim.c.o /home/itwrx/.cache/nim/winimx_r/@mwinimx.nim.c.o  -lm   -L/usr/local/lib -L/usr/local/lib -Wl,-rpath=.:/usr/local/lib:/usr/pkg/lib:/usr/X11R6/lib'
    Prompt: Build failed for 'neoid@0.3.1', would you like to try installing 'neoid@#head' (latest unstable)? [y/N]
    Answer: n
    Prompt: Build failed for 'quickcrypt@0.1.4', would you like to try installing 'quickcrypt@#head' (latest unstable)? [y/N]
    Answer: n
       Tip: 40 messages have been suppressed, use --verbose to show them.
     Error: Aborting installation due to build failure

```

I'm trying to rebuild my nim application i use on linux in production, but for my new replacement server which is in testing phase and runs OpenBSD. Besides this application, i would like to be able to use your package for other programs in the future, as it was very nice and easy to use.

Thanks

**Comment by theAkito** [comment]
Greetings!

> Besides this application, i would like to be able to use your package for other programs in the future, as it was very nice and easy to use.

First of all, thank you so much for the kind feedback!

I look into this issue. 😃 

As I usually do not use *BSD distributions, I don't know how quickly I will be able to fix this issue, but I will do my best.

Kind regards! 😄

**Comment by ITwrx** [comment]
Thanks a lot! No huge rush. It will be at least a month before i'll be ready to put the server into production, assuming all else goes well. 

It's been many/several years since i've tried out any BSD myself, but am looking to move to OpenBSD in production for certain purposes if testing works out. Liking it very much so far, except it's not used as much, so these types of things are bound to come up. 

Feel free to provide an XMR, BTC address for donating towards your work in supporting OpenBSD.

**Comment by theAkito** [comment]
The referenced fix was tested with Nim 1.4.0 on [FuguIta](http://fuguita.org/) through Hyper-V Gen 1.

@ITwrx 

Should work now. 😄

**Comment by ITwrx** [comment]
thanks a lot! will try it out soon. I agree with your tactic on the fix. I, personally don't even want the winim dependency when using linux either. I noticed it when writing my application and wondered why that was there.

**Comment by theAkito** [comment]
> I, personally don't even want the winim dependency when using linux either.

I have it only in there, because I actually cross-compile to Windows a lot, so I kind of need it there. However, if a user really doesn't want the dependency, I'm sure they can manually `nimble remove` it once the needed package, in this case `quickcrypt`, was installed.

The other reason for having the dependency enabled by default is, that I expect users to develop on their developer machines. If you use heavy IDEs like, for example, IntelliJ IDEA and/or Visual Studio, anyway, like I do, then you do not care about a single dependency more, as you have bloated your PC already with those huge IDEs. 😄 

Due to aforementioned reasons I think it should be acceptable to have one or a couple more dependencies that are perhaps optional for a group of users, in the requirements of the package you need.

**Comment by ITwrx** [comment]
> However, if a user really doesn't want the dependency, I'm sure they can manually nimble remove it once the needed package, in this case quickcrypt, was installed.

Sounds good to me, i hadn't thought of that. I've been out of nim for a couple weeks so all bets are off. :)
